### ISSUE TITLE
Insecure Landing Page

### ISSUE THREAD

**Issue by sharpsays** [jiwoochun/sailpointwp#21]
@jiwoochun I found another page on sailpoint.com that is giving an insecure alert via Firefox. See attached image. It may just be an image issue, but wanted to flag just in case.
![screen shot 2017-10-26 at 1 54 25 pm](https://user-images.githubusercontent.com/32499501/32073399-84c809aa-ba5b-11e7-824a-fc76a3ac518f.png)

**Comment by jiwoochun** [comment]
There was html img tag in the page that is pointing at `http://{some image name}` instead of `https://{some image name}`. 

Also saw a couple other issues - 
1. Template used is logo header template instead of default template
2. Eloqua errors related to issue #18 

Both of these were fixed. An issue will be opened up to switch all pages with a `logo-header-template` to `default template`.
