### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by maxram7** [jiwoochun/sailpointwp#26]
Hi there,

When we updated the URL's for the blog to /blog, we broke some old redirects I think, because we are now pulling in a bunch of 404 errors for pages that don't exist but are somehow being indexed. Would you mind taking a look at it? We may need to update the robots file as well. 
There may also be a category issue so we appended those URL's to the bottom of the list in case it is related. The other tab has the remaining 404 errors being pulled in that need to be investigated. 

The attached has the list of pages associate with this issue. 

[171106 www-sailpoint-com_20171106T203410Z_CrawlErrors.xlsx](https://github.com/jiwoochun/sailpointwp/files/1447737/171106.www-sailpoint-com_20171106T203410Z_CrawlErrors.xlsx)

**Comment by jiwoochun** [comment]
urls under `tag` directory are back. 
We should probably create a template for these pages in the near future. Because they're still out there and can be seen, should we put a redirect for all pages under `/tag` to the `homepage`.  

I also think we should do some redirects for all the 404 `/category` pages to `/blog`. 

@maxram7 let me know if you want me go ahead and do this.

**Comment by maxram7** [comment]
I think we can redirect both /category and /tag to /blog.

**Comment by jiwoochun** [comment]
all URLs on xls is now redirecting to `/blog`

Closing this issue and will open up a new issue to re-investigate why the redirects disappeared in the first place.
